---
- name: install haproxy server
  yum: name=haproxy state=present

- name: copy file config
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    backup: yes

- name: edit file rsyslog
  template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.conf
    backup: yes

- name: create log file for haproxy
  template:
    src: haproxy.conf.j2
    dest: /etc/rsyslog.d/haproxy.conf
    backup: yes

- name: start haproxy service
  service: name=haproxy state=started enabled=yes
