---
- name: download and install repo remi
  shell: wget http://rpms.remirepo.net/enterprise/remi-release-7.rpm
  args:
    chdir: /root

- name: install rpm remi
  shell: rpm -Uvh remi-release-7*.rpm
  args:
    chdir: /root

- name: install php 7.2
  yum:
    name: '{{ item }}'
    enablerepo: remi-php72
    state: present
  with_items:
    - php 
    - php-mysql 
    - php-bcmath 
    - php-cli 
    - php-common 
    - php-devel 
    - php-embedded 
    - php-enchant 
    - php-mbstring 
    - php-mcrypt 
    - php-pdo 
    - php-xml
