---
- name: chattr file resolv.conf
  command: chattr +i /etc/resolv.conf

- name: Enable gateway card eth1
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth1
    regexp: '^#GATEWAY='
    line: 'GATEWAY=172.16.100.1'

- name: disable gateway card eth0
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth0
    regexp: '^GATEWAY='
    line: '#GATEWAY=192.168.1.1'

#- name: re chattr file resolv.conf
    #command: chattr -i /etc/resolv.conf


- name: restart network
  service:
    name: network
    state: restarted

