---

- name: copy zabbix rpm file
  copy:
    src: templates/zabbix-agent-3.2.9-1.el7.x86_64.rpm
    dest: /tmp/zabbix-agent-3.2.9-1.el7.x86_64.rpm

- name: install zabbix rpm file from local
  yum:
    name: /tmp/zabbix-agent-3.2.9-1.el7.x86_64.rpm
    state: present

- name: copy lld-disks.py
  copy:
    src: templates/lld-disks.py
    dest: /usr/local/bin/lld-disks.py

- name: copy userparameter_diskstats.conf
  template:
    src: userparameter_diskstats.conf
    dest: /etc/zabbix/zabbix_agentd.d/userparameter_diskstats.conf

- name: copy userparameter_sockstat.conf
  template:
    src: userparameter_sockstat.conf
    dest: /etc/zabbix/zabbix_agentd.d/userparameter_sockstat.conf

- name: get hostname to config zabbix agentd
  shell: hostname
  register: hst

- name: config hostname zabbix agentd
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: '^Hostname='
    line: Hostname={{ hst.stdout }}

- name: config IP server zabbix agentd
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: '^Server='
    line: Server=192.168.219.34

- name: config IP ServerActive zabbix agentd
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: '^ServerActive='
    line: ServerActive=192.168.219.34

- name: start zabbix agent service
  systemd:
    state: started
    name: zabbix-agent
    enabled: yes

